### ISSUE TITLE
Main renderer thread locks OutputSurfaces collection.

### ISSUE THREAD

**Issue by Zeracronius** [Syncaidius/MoltenEngine#18]
The Renderer_main thread locks the OutputSurfaces collection preventing adding additional output windows while presenting.

Main thread is trying to add additional output surfaces here:
https://github.com/Syncaidius/MoltenEngine/blob/ddbd23543c39b40e372a9248ae862e4b3a11806f/Molten.Samples/MultiWindowGame.cs#L46

Renderer is locking the collection here:
https://github.com/Syncaidius/MoltenEngine/blob/ddbd23543c39b40e372a9248ae862e4b3a11806f/Molten.Platform/Graphics/MoltenRenderer.cs#L253

Which then locks the collection until it has finished presenting every surface while the main thread is in a spin-lock causing a race condition.

![billede](https://user-images.githubusercontent.com/64704191/142737456-60b3ffa0-470d-41d7-bbd7-528ad511bd39.png)

**Comment by Syncaidius** [comment]
This is fixed after the switch from [SharpDX](https://github.com/sharpdx/SharpDX) to [Silk.NET](https://github.com/dotnet/Silk.NET)
