### ISSUE TITLE
NRE in SettingValue

### ISSUE THREAD

**Issue by Zeracronius** [Syncaidius/MoltenEngine#21]
Instantiating a new in-memory SettingBank trigger a null reference exception on SettingValue once you call Apply after setting the values because _value is null.

https://github.com/Syncaidius/MoltenEngine/blob/40cb87749b2e3ccc459a6d70d228d7b01495f60e/Molten.IO/Settings/SettingValue.cs#L63

**Comment by Syncaidius** [comment]
As soon as I'm done with the [Silk.NET](https://github.com/Syncaidius/MoltenEngine/tree/SilkDotNet) branch, I'll get this fixed.

**Comment by Syncaidius** [comment]
This has been fixed in 3c98e5dd75546a66db65cee6d252bb8a36eb8673. I'll close this once we confirm there are no further issues.
