### ISSUE TITLE
MouseDevice Movement Getting Stuck

### ISSUE THREAD

**Issue by Syncaidius** [Syncaidius/MoltenEngine#48]
Mouse movement gets stuck after being dragged and then stopping. The `Delta` property does not reset to zero after movement stops.

**Comment by MateiIonutEduard** [comment]
Hi @Syncaidius! Give it to me.
I will fix this bug.

**Comment by Syncaidius** [comment]
Fixed in https://github.com/Syncaidius/MoltenEngine/commit/ded16f9f4ed354d79696f63531a6d999e78344aa
